

export const metadata = {
  title: 'QR CODE GEN | Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between">
      <div className="min-h-screen">
        Hello
      </div>
    </main>
  )
}
