import QRCategory from '~/components/Homepage/QRCategory';

export const metadata = {
    title: 'QR CODE GEN | Home',
    description: 'Generated by create next app',
};

export default function Home() {
    return (
        <main className="flex min-h-screen w-full overflow-x-hidden flex-col items-center justify-between font-sans-serif">
            <div className="min-h-screen w-screen flex flex-col my-4 items-center">
                <div className="p-4 mb-12">
                    <h1 className="text-4xl font-bold text-center mb-4">
                        TẠO VÀ TÙY CHỈNH QR CODE CỦA BẠN
                    </h1>
                    <p className="text-center text-xl text-gray-600">
                        Dễ dàng tạo và quản lý QR code của bạn
                    </p>
                </div>

                <QRCategory />
            </div>
        </main>
    );
}
